apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - model-a-scaledobject.yaml
  - model-b-scaledobject.yaml

patches:
  - patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: model-a-hpa
        namespace: llm-d-sim
  - patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: model-b-hpa
        namespace: llm-d-sim
